const Company = require('../models/companyModel');


exports.getAllCompanies = async (req, res) =>{
  try{
    
    const getAllComp = await Company.find();

    res
    .status(200)
    .json({ data: getAllComp });

  //Catching any errors 
  } catch (err){
      res
      .status(400)
      .json({ message: err.message });
  }
};

//Creating New companies Request using Post
exports.createNewCompany = async(req,res) =>{

  try{
    const data = req.body;
    const newCompany = await Company.create(data);

    res
    .status(201)
    .json({
      message: `Company created succesfully. Company Id ${newCompany.companyId}`,
      autoGeneratedid: newCompany._id
    });

  } catch (err){
      res
      .status(400)
      .json({ message: err.message });
  }
};
//get the commpany using companyId saved in model
exports.getCompanyById = async (req, res) => {
  try {
    const {companyId} = req.params;
    const companyFound = await Company.findOne({companyId: companyId})

    if(!companyFound) {
      return res.status(404).json({
        message: 'No company found under this id'
      });
    }

    res.status(200).json({
      message: 'Company retrieved successfully.',
      companyInfo: companyFound,
  });
  } catch {
    console.error('Error retrieving company: ', error.message);
        res.status(500).json({
            message: 'Failed to retrieved company.',
            error: error.message
  
        });
      }

}

//Getting an Company using id - auto generated by Mongo
exports.getCompany = async (req, res) =>{
  try {
    const id = req.params.eid;
    const comp = await Company.findById(id);

    if(comp === null) {
      throw Error("Company not found");
    }
    
    res
    .status(200)
    .json({ data: comp });

  } catch (err) {
      res
      .status (404)
      .json({ message: err.message });
  }
};

//Updating an Company using put
exports.updateCompany = async(req, res) =>{
  try{
    await Company.findByIdAndUpdate(
      req.params.companyId, 
      req.body, 
      { new: true, runValidators: true }
    );

    res
    .status(200)
    .json({ message: "Company details updated successfully" });

  } catch(err) {
      res
      .status(400)
      .json({ message: err.message });
  }
       
};

//Deleting an Company using delete
exports.deleteCompany = async(req,res) =>{
  try {
    const id = req.query.companyId;
    await Company.findByIdAndDelete(id);

    res
    .status(200)
    .json({              
      message: `Company deleted successfully ${req.query.eid} `
    });
  } catch(err) {
        res
        .status(400)
        .json({ message: err.message });
  }        
};