const mongoose = require('mongoose');

const accessSchema = new mongoose.Schema({
    accessId: {
        type: mongoose.Schema.Types.ObjectId,
        default: new mongoose.Types.ObjectId, // the accessId is auto generated by default when the access record created
        required: [true, 'Access ID is required.']
    },
    visitorId: {
        type: mongoose.Schema.Types.ObjectId,
        default: new mongoose.Types.ObjectId,
        required: [true, 'Visitor ID is required'] //// the visitorId is auto generated by default when the access record created
    
    },
    accessCode: {
        type: String,
        required: [true, 'Access Code required to enter the building']
        
    },
    type: {
        type: String,
        enum: ['visitor', 'delivery', 'admin']
        
    },
    expiresAt: {
        type: Date
    },
    isActive: {
        type: Boolean,
        default: true
    },
    createdAt: {
        type: Date,
        default: Date.now
    }
});


const access = mongoose.model("Access", accessSchema);
module.exports = access;
